### ISSUE TITLE
Google Colab Running Problem

### ISSUE THREAD

**Issue by Rafat97** [amzn/multiconer-baseline#4]
Thanks for providing this baseline code..

## Problem

![image](https://user-images.githubusercontent.com/21246862/140552244-a4b69e40-3b86-4f18-826f-175a960b9069.png)

I was trying this code on Google Colab. When I try to install all the packages.  First, I found this package version related problem. 

Can you please check this `requirements.txt` file again? 

Thank you.

Colab Code Link-
https://colab.research.google.com/drive/10hv8rrxvul8bzmQxsoagJ-w7kEinqquZ?usp=sharing

## My solution
I was trying to solve this problem. To solve this I use this code-
https://colab.research.google.com/drive/1iLP-2tQxwKVAp-LjsE1OxroCGX4Bh3QE?usp=sharing

Please check the code and give a feedback. Is this OK or not?  Thank you.

**Comment by bhuiyanmobasshir94** [comment]
I think this will work if you remove the versions from your `requirements.txt` file. Try it and let us know if this resolves your issue.

**Comment by Rafat97** [comment]
> I think this will work if you remove the versions from your `requirements.txt` file. Try it and let us know if this resolves your issue.

Thank you @bhuiyanmobasshir94 ,For giving this solution. ❤️‍🔥
I will try you solution. And give feedback as early as possible. 
Currently I use [this](https://colab.research.google.com/drive/1iLP-2tQxwKVAp-LjsE1OxroCGX4Bh3QE?usp=sharing) Colab template.

**Comment by bhuiyanmobasshir94** [comment]
@Rafat97 I think installing just `allennlp` and `pytorch-lightning` is good to go with google colab.
